#!/usr/bin/env bash
# =============================================================================
#  ThinClient OS — Install-to-disk
#  Installed to: /opt/thinclient/bin/thinclient-install
#
#  Persists the running live appliance onto an internal disk so the machine
#  boots the thin client from local storage (no USB needed). Run this ONCE on
#  a reference machine, then clone the fleet with Clonezilla (docs/CLONEZILLA.md).
#
#  What it does:
#    1. Partitions the target disk: GPT + 512M EFI (FAT32) + rest ext4 root.
#    2. rsyncs the live root filesystem onto the new root.
#    3. Generates /etc/fstab, removes live-only packages, installs GRUB
#       (UEFI and BIOS), and rebuilds the initramfs.
#
#  DESTRUCTIVE: everything on the chosen disk is erased. You are asked to type
#  the disk name to confirm.
#
#  Usage:
#     sudo thinclient-install [/dev/sdX]     # interactive if disk omitted
# =============================================================================
set -euo pipefail

TARGET_MNT="/mnt/target"
LOG="/var/log/thinclient/install.log"

log() { printf '%s [install] %s\n' "$(date --iso-8601=seconds 2>/dev/null || date)" "$*" | tee -a "$LOG"; }
die() { printf '\033[1;31m[x]\033[0m %s\n' "$*" >&2; exit 1; }

[[ "$(id -u)" -eq 0 ]] || die "Run as root: sudo thinclient-install"
mkdir -p "$(dirname "$LOG")"

# --------------------------------------------------------------------------- #
# 1. Choose the target disk.
# --------------------------------------------------------------------------- #
DISK="${1:-}"
if [[ -z "$DISK" ]]; then
  echo "Available disks:"
  lsblk -d -o NAME,SIZE,MODEL,TYPE | grep -E 'disk$' || true
  echo
  read -r -p "Target disk to ERASE and install onto (e.g. /dev/sda): " DISK
fi
[[ -b "$DISK" ]] || die "Not a block device: $DISK"

# Refuse to install onto the live boot medium itself.
LIVE_SRC="$(findmnt -no SOURCE /run/live/medium 2>/dev/null || true)"
if [[ -n "$LIVE_SRC" && "$LIVE_SRC" == "$DISK"* ]]; then
  die "$DISK appears to be the live boot medium. Choose the internal disk."
fi

echo
echo "  !!  ALL DATA ON ${DISK} WILL BE DESTROYED  !!"
lsblk "$DISK" || true
echo
read -r -p "Type the disk name (${DISK}) to confirm: " CONFIRM
[[ "$CONFIRM" == "$DISK" ]] || die "Confirmation did not match. Aborting."

# Partition suffix: /dev/sda -> sda1 ; /dev/nvme0n1 -> nvme0n1p1
part() { case "$DISK" in *[0-9]) echo "${DISK}p${1}";; *) echo "${DISK}${1}";; esac; }
EFI_PART="$(part 1)"; ROOT_PART="$(part 2)"

# --------------------------------------------------------------------------- #
# 2. Partition + format.
# --------------------------------------------------------------------------- #
log "Partitioning ${DISK} (EFI=${EFI_PART}, root=${ROOT_PART})"
umount -R "$TARGET_MNT" 2>/dev/null || true
wipefs -a "$DISK"
sgdisk --zap-all "$DISK"
sgdisk -n1:0:+512M -t1:ef00 -c1:"EFI" "$DISK"
sgdisk -n2:0:0     -t2:8300 -c2:"THINCLIENT_ROOT" "$DISK"
partprobe "$DISK"; sleep 2

log "Formatting partitions"
mkfs.vfat -F32 -n EFI "$EFI_PART"
mkfs.ext4 -F -L THINCLIENT_ROOT "$ROOT_PART"

# --------------------------------------------------------------------------- #
# 3. Mount + copy the live root filesystem.
# --------------------------------------------------------------------------- #
log "Mounting target"
mkdir -p "$TARGET_MNT"
mount "$ROOT_PART" "$TARGET_MNT"
mkdir -p "$TARGET_MNT/boot/efi"
mount "$EFI_PART" "$TARGET_MNT/boot/efi"

log "Copying system (rsync) — this takes a few minutes"
rsync -aHAXx --info=progress2 \
  --exclude=/dev/* --exclude=/proc/* --exclude=/sys/* --exclude=/tmp/* \
  --exclude=/run/* --exclude=/mnt/* --exclude=/media/* --exclude=/lost+found \
  --exclude=/live --exclude="/run/live" --exclude="/lib/live/mount" \
  --exclude=/var/log/thinclient/* \
  / "$TARGET_MNT/"

# --------------------------------------------------------------------------- #
# 4. fstab.
# --------------------------------------------------------------------------- #
log "Writing /etc/fstab"
ROOT_UUID="$(blkid -s UUID -o value "$ROOT_PART")"
EFI_UUID="$(blkid -s UUID -o value "$EFI_PART")"
cat >"$TARGET_MNT/etc/fstab" <<EOF
# ThinClient OS — generated by thinclient-install
UUID=${ROOT_UUID}  /          ext4  errors=remount-ro,noatime  0 1
UUID=${EFI_UUID}   /boot/efi  vfat  umask=0077                 0 1
tmpfs              /tmp       tmpfs defaults,nosuid,nodev       0 0
EOF

# --------------------------------------------------------------------------- #
# 5. Chroot: drop live packages, install GRUB, rebuild initramfs.
# --------------------------------------------------------------------------- #
log "Preparing chroot"
for fs in dev dev/pts proc sys run; do
  mkdir -p "$TARGET_MNT/$fs"
  mount --bind "/$fs" "$TARGET_MNT/$fs"
done

UEFI_MODE=0; [[ -d /sys/firmware/efi ]] && UEFI_MODE=1

log "Installing bootloader inside chroot (UEFI_MODE=${UEFI_MODE})"
chroot "$TARGET_MNT" /bin/bash -euo pipefail <<CHROOT
export DEBIAN_FRONTEND=noninteractive

# Remove live-only components so it boots as a normal installed system.
apt-get -y purge live-boot live-boot-initramfs-tools live-config live-config-systemd 2>/dev/null || true
apt-get -y autoremove 2>/dev/null || true

# GRUB defaults: silent, kiosk-friendly kernel command line.
sed -i 's|^GRUB_CMDLINE_LINUX_DEFAULT=.*|GRUB_CMDLINE_LINUX_DEFAULT="quiet splash loglevel=0 vt.global_cursor_default=0 rd.systemd.show_status=false systemd.show_status=false"|' /etc/default/grub || true
sed -i 's|^GRUB_TIMEOUT=.*|GRUB_TIMEOUT=1|' /etc/default/grub || true
grep -q '^GRUB_TIMEOUT_STYLE' /etc/default/grub || echo 'GRUB_TIMEOUT_STYLE=hidden' >> /etc/default/grub

# UEFI bootloader.
if [ "${UEFI_MODE}" = "1" ]; then
  grub-install --target=x86_64-efi --efi-directory=/boot/efi --bootloader-id=thinclient --recheck
fi
# BIOS bootloader (also install for hybrid / fallback machines).
grub-install --target=i386-pc --recheck ${DISK} || true

update-grub
update-initramfs -u -k all

# Make sure our services are enabled on the installed system.
systemctl set-default graphical.target
systemctl enable thinclient-firstboot.service thinclient-x.service thinclient-watchdog.service || true
CHROOT

# --------------------------------------------------------------------------- #
# 6. Cleanup.
# --------------------------------------------------------------------------- #
log "Unmounting"
for fs in run sys proc dev/pts dev; do umount -l "$TARGET_MNT/$fs" 2>/dev/null || true; done
umount -R "$TARGET_MNT" 2>/dev/null || true

log "Installation complete on ${DISK}."
printf '\n\033[1;32mInstall complete.\033[0m\n'
cat <<EOF
  * Remove the USB stick and reboot: sudo reboot
  * The machine now boots the ThinClient appliance from ${DISK}.
  * To deploy to the fleet, clone ${DISK} with Clonezilla — see
    /opt/thinclient/docs/CLONEZILLA.md
EOF
